### ISSUE TITLE
Block 23057 WARN, Error occured on chain sync with Peer, Data not found on disk: load data

### ISSUE THREAD

**Issue by mrhedstrom** [xelis-project/xelis-blockchain#48] opened 2024-04-27 17:54 UTC
I have tried to sync the blockchain twice now but get stuck on block 23056 and all peers generates the same error:

`[2024-04-27] (17:39:57.300) [WARN ] [xelis_daemon::p2p]              | Error occured on chain sync with Peer[connection: Connection[peer: ???.???.???.???:2125, read: 130 KiB, sent: 1.9 KiB, key rotation (in/out): (1/1), connected since: 5s, closed: false], id: 1580593161845417619, topoheight: 39745, top hash: 549fd194009b930ea003819240bc8d403f12e68ea2d81f4c2ee67f890270ea29, height: 37760, pruned: No, priority: true, tag: None, version: 1.9.4-6a4e306, fail count: 0, out: true, peers: 0]: Data not found on disk: load data`

**Comment by mrhedstrom** [comment] 2024-04-27 20:34
I took the db from my docker linux environment and continued on a windows machine and it got past this block. After 200 blocks I stopped the windows daemon, copied back the db and it started working in docker from where windows daemon left off. So issue was only in docker linux environment on this block. 
I'm running docker version v1.9.3

**Comment by mrhedstrom** [comment] 2024-04-27 21:03
It happened again on block 26504. It is getting stuck on block 26503 and the same error from all peers.

**Comment by Catjrrey** [comment] 2024-04-28 12:02
Have you found a solution to the problem? I am also facing the same issue as you.

**Comment by Slixe** [comment] 2024-04-28 12:24
Can you try using dev branch ? Resync from 0, delete mainnet folder and start the daemon and keep me updated

**Comment by mrhedstrom** [comment] 2024-04-28 12:24
No, but I did a workaround. I moved the db to a windows client and ran with command --allow-boost-sync
When the whole blockchain was synced I moved the db back to the data mount of my docker and started the daemon.

**Comment by mrhedstrom** [comment] 2024-04-28 12:28
> Can you try using dev branch ? Resync from 0, delete mainnet folder and start the daemon and keep me updated

Where can I find a prebuilt docker image from dev branch? I have downloaded the docker image prebuilt. I don’t know how to build the docker image.

**Comment by Neomail2** [comment] 2024-05-21 18:02
Hello, same problem for me on windows daemon
![image](https://github.com/xelis-project/xelis-blockchain/assets/120675713/f838efbd-9c60-4082-996e-89cad4ebe1d5)
i already deleted the directory "mainnet" but every time it download all the blockchain it stop with that error

**Comment by Airlineben** [comment] 2024-05-21 18:58
> Hello, same problem for me on windows daemon ![image](https://private-user-images.githubusercontent.com/120675713/332531531-f838efbd-9c60-4082-996e-89cad4ebe1d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTgxOTUsIm5iZiI6MTcxNjMxNzg5NSwicGF0aCI6Ii8xMjA2NzU3MTMvMzMyNTMxNTMxLWY4MzhlZmJkLTljNjAtNDA4Mi05OTZlLTg5Y2FkNGViZTFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxODU4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTQ3YmIxYTU1ZDYyNzE4NjFhMjU1ZGJlODlkMjkxMGRlNDQ4NTVhYjY0ODc3MTFmMjA2ZDM5N2FhMDZiMWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gLMgvo_-erOUAgBpezgtdLRINeAK0Q8LmHJyDIG71og) i already deleted the directory "mainnet" but every time it download all the blockchain it stop with that error on that same block 173 990 (i did already 3 times)
> 
> Any idea ?

I am the same.  Glad to know I am not the only one.

**Comment by Neomail2** [comment] 2024-05-21 22:08
Some other with the same problem ?

**Comment by CEOuysal** [comment] 2024-05-22 12:28
![Xelis error](https://github.com/xelis-project/xelis-blockchain/assets/170529334/187dc4bd-3921-48dc-ba3c-85149f7dcbd8)

same problem !

**Comment by solopool** [comment] 2024-05-23 05:12
@Neomail2 @Catjrrey  same problem on height: 163451 and topoheight: 173990 with --allow-boost-sync and without it.

![xel](https://github.com/xelis-project/xelis-blockchain/assets/34550374/a7f199b3-06ad-490b-83d4-992035a8d6f9)

**Comment by Slixe** [comment] 2024-05-23 07:47
Yes 173990 stuck block is due to a DAG reorg that made a valid proof into invalid, this will be fixed shortly today. I found the cause and will release the v1.12. If you cant wait, join the discord server and download the backup in support channel.

**Comment by SammyBoySLO** [comment] 2024-05-24 06:20
Obviously problem is not yet solved. I'm still stucked on block 173990

**Comment by KarelVydra** [comment] 2024-05-25 16:10
@Slixe I have installed v1.12, the problem persists, I'm still stucked on then block 173990.

**Comment by Slixe** [comment] 2024-05-25 16:37
do `pop_blocks 10` then let it sync again

**Comment by Neomail2** [comment] 2024-05-25 17:24
Done but now stucked on block 174007 with the same error

**Comment by KarelVydra** [comment] 2024-05-25 19:26
> Done but now stucked on block 174007 with the same error (i'm on V1.12)

try to repeat pop_blocks 10 again. It worked for me

**Comment by Neomail2** [comment] 2024-05-25 22:37
unfortunately not :/  locked again on block 173990

**Comment by TRam-7** [comment] 2024-05-26 08:09
same issue here, locked again on block 173990 after a few pop_blocks

**Comment by TRam-7** [comment] 2024-05-26 14:16
Solved it by pop_blocks 20 then exit deamon, start deamon with boost sync, 2 x pop_blocks 20 and sync again ...

**Comment by JRodb** [comment] 2024-05-26 21:04
Same issue here, apply the  solution above but does not work, still stuck in block 173356

**Comment by Slixe** [comment] 2024-05-26 21:10
delete mainnet folder and do a full resync

**Comment by JRodb** [comment] 2024-05-26 21:45
Done it, and again get stuck in block 173329 :(

**Comment by 7runks** [comment] 2024-05-28 06:49
> do `pop_blocks 10` then let it sync again

How can I do that?

I'm on windows so, command line? --> xelis_daemon.exe --pop_blocks 10? it did not work, this command does not exist.

Anybody can help me with that?

**Comment by Slixe** [comment] 2024-07-04 23:44
Closing as completed, if you guys have any new issue, please open a new one.

Thanks for running a node!

**Closed by Slixe** 2024-07-04 23:44 UTC
